### ISSUE TITLE
possible invalid value "I" in N_CONS column

### ISSUE THREAD

**Issue by jhpoelen** [GoMexSI/abascal#3]
@tmitchell1 @iabascal Great to see that your data made it into the repository! 

From an automated data validation, it appears that a value "I" (capital i) appears in column N_CONS in line 533 of Prey.csv . This non-numeric value is causing an error reading the data for use in GloBI and, by extension, in GoMexSI's website. 

Please correct this error and let me know if you need help doing so.

Some (cryptic) error message from https://travis-ci.org/GoMexSI/abascal/builds/258624159 -
```
StudyImporterForGitHubData:63 - failed to import data from repo [GoMexSI/abascal]
org.eol.globi.data.StudyImporterException: failed to parse key [totalNumberConsumed] with value [I]
	at Caused by: java.lang.NumberFormatException: For input string: "I"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.eol.globi.data.StudyImporterForGoMexSI2.integerValueOrNull(StudyImporterForGoMexSI2.java:297)
	... 7 more

**Comment by jhpoelen** [comment]
I took the liberty to replace the value "I" to "1".
